# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ local_api_specification ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - name: Create contracts directory
      run: mkdir ../contracts && ls -l ../   
#     - uses: actions/checkout@v2.1.0
#       with:
#         repository: znsio/specmatic-order-contracts
#         path: ../contracts/main
    - name: Grant execute permission for gradlew
      run: pwd
      working-directory: contracts
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: main
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: main
